echo "it works again"
echo "hey you"
echo "blah blah"
echo "yo man"
echo "added to mnordsletten"
echo "hey you"
echo "again we go"
echo "you are great"
echo "good job man"
echo "if this works you are amazing"
echo "hey you"
echo "could be grerat"
echo "yoe"
echo "hey"
echo "amazing man"
exit
